
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Button button10;
	
	private global::Gtk.Button button20;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Button button50;
<<<<<<< HEAD
	
	private global::Gtk.Button button1;
=======
>>>>>>> 94d06f55f3f632d0ffcd2faf2d98a55033ad9b34

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button ();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString ("10x10");
		this.vbox3.Add (this.button10);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button10]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button20 = new global::Gtk.Button ();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString ("20x20");
		this.vbox3.Add (this.button20);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button20]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button50 = new global::Gtk.Button ();
		this.button50.CanFocus = true;
		this.button50.Name = "button50";
		this.button50.UseUnderline = true;
		this.button50.Label = global::Mono.Unix.Catalog.GetString ("50x25");
		this.vbox1.Add (this.button50);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button50]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
<<<<<<< HEAD
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Personalizado");
		this.vbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox3.Add (this.vbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
=======
		this.vbox3.Add (this.vbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
>>>>>>> 94d06f55f3f632d0ffcd2faf2d98a55033ad9b34
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 341;
<<<<<<< HEAD
		this.DefaultHeight = 134;
=======
		this.DefaultHeight = 99;
>>>>>>> 94d06f55f3f632d0ffcd2faf2d98a55033ad9b34
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
